local status, prettier = pcall(require, "prettier")
if (not status) then return end

prettier.setup {
  bin = 'prettierd',
  filetypes = {
    "css",
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "json",
    "scss",
    "less",
    "graphql",
    "markdown",
    "vue",
    "html",
    "svelte",
    "lua",
    "go",
    "rust",
    "php",
    "ruby",
    "haskell",
    "ocaml",
    "swift",

  },
  cli_options = {
    arrow_parens = "always",
    bracket_spacing = false,
    bracket_same_line = false,
    embedded_language_formatting = "auto",
    end_of_line = "lf",
    html_whitespace_sensitivity = "css",
    -- jsx_bracket_same_line = false,
    jsx_single_quote = true,
    print_width = 80,
    prose_wrap = "preserve",
    quote_props = "as-needed",
    semi = false,
    single_attribute_per_line = true,
    single_quote = true,
    tab_width = 2,
    trailing_comma = "es5",
    use_tabs = true,
    vue_indent_script_andiii_style = false,
  },
}
